### ISSUE TITLE
RFC: Reevaluate time related fields

### ISSUE THREAD

**Issue by kierangillen** [artsy/metaphysics#1650]
Currently `start_at` and `end_at` timestamps do not record a timezone. We ask, and rely on, editors of cms.artsy.net, admin-fairs.artsy.net and auctions.artsy.net to input timestamps offset by UTC. E.g. if an auction is starting at 12pm Hong Kong Standard Time (GMT+8) we enter the time offset by 8 hours, `2019-11-01T04:00:00+00:00`.  

This has worked fine for Auctions, as Artsy's auction team know to offset the time using a third party site. However, when Partners and other editors enter the time into the input in admin-fairs.artsy.net and cms.artsy.net it is often unclear or laborious and the content is entered incorrectly. 

I'm proposing that we add a timezone selection to cms.artsy.net, admin-fairs.artsy.net and auctions.artsy.net datetime inputs to correctly record timestamps and to also make the content entry easier and explicit. I'm also proposing we add a new set of guidelines, or perhaps a design system, to outline the ways different models display time.

To make this transition seamless I'm proposing these steps:

1. The current `start_at` and `end_at` dates in Metaphysics should have their timezone data stripped and returned as `+00:00`, i.e. `2019-11-01T04:00:00+05:00` → `2019-11-01T04:00:00+00:00`, so to always return this timestamp with it's original `+00:00`, in preparation for updating Gravity with timezones.

2. Run a migration that updates Gravity's current timestamps stamped with a timezone based on the partner or galleries current timezone based on location, i.e. `2019-11-01T04:00:00+00:00` → `2019-11-01T04:00:00+05:00`.

3. Create new `startAt` and `endAt` fields in metaphysics that return the timestamp with encoded timezone in ISO 8601 format, setting us up to slowly deprecate the snake_case variants.

4. Create guidelines for returning text fields created in Metaphysics instead of using ISO 8601 timestamps in client applications. These could potentially live in Palette. E.g. for fair and show model we can return `formattedOpeningHours` as "Opens Mar 29 at 4:00pm" instead of formatting the timestamp in the client. A notion doc has been started on this subject: https://www.notion.so/artsy/Formatting-Time-f6f4aaeeba414583a207013fec5a9794

This is not just a backend change, but also a holistic overview for how and where we're using time. In many cases we want to use time relative to a place, a fair should perhaps always show "Opens Mar 29 at 4:00pm," no matter where the user is viewing from. An auction may need to show "Starts Mar 29 at 4:00pm EST" and be dynamic based on the users' location. Through creating a system of guidelines and setting up metaphysics to handle most (or perhaps all) of our date formatting, we can make these use cases explicit in perpetuity.

**Comment by damassi** [comment]
I wonder if there are any articles online that detail timezone migrations, hiccups and gotchas. Time, and timezones in particular, are notorious for their implementation complexity and so it would be good to maybe aggregate a few case studies in an effort to clarify the level of effort required.

**Comment by anandaroop** [comment]
Because computers + times + dates + timezones are always harder than you think 😅 , I'm linking to two articles that helped clarify a lot of this for me:

- https://zachholman.com/talk/utc-is-enough-for-everyone-right — lighthearted but very informative overview

- https://codeblog.jonskeet.uk/2019/03/27/storing-utc-is-not-a-silver-bullet — persuasive argument that storing future events' datetimes as a UTC+offset timestamp is _not_ a reliable solution given the mutability of the world's time zones ([not a theoretical problem](https://www.google.com/search?client=safari&rls=en&q=eu+time+zone+debate&ie=UTF-8&oe=UTF-8))

**Comment by alloy** [comment]
I’m frankly surprised that we ever thought it was good enough to have people think about calculating their own offsets. I think we should absolutely have a good UI for people to input a time plus offset without needing to do any calculations on their own.

While there are many other things to consider–such as UTC+offset not necessarily being reliable for future events, as @anandaroop points out–having UTC+offset would actually allow us to take steps when we are aware of and want to deal with such situations.

So I’m broadly 👍 on this.

----

Having said that, I’m not entirely clear about some specific steps in this RFC.

> Currently `start_at` and `end_at` timestamps do not record a timezone.

Are we talking about fields named like that _anywhere_ in the schema? And does it also apply to `*_start_at` etc?

> 1. The current `start_at` and `end_at` dates in Metaphysics should have their timezone data stripped and returned as `+00:00`, i.e. `2019-11-01T04:00:00+05:00` → `2019-11-01T04:00:00+00:00`, so to always return this timestamp with it's original `+00:00`, in preparation for updating Gravity with timezones.
>
> 2. Run a migration that updates Gravity's current timestamps stamped with a timezone based on the partner or galleries current timezone based on location, i.e. `2019-11-01T04:00:00+00:00` → `2019-11-01T04:00:00+05:00`.

Why can’t we respect those that were already entered with offsets?

**Comment by alloy** [comment]
Hmm, but then where are those offsets, that you are proposing to truncate, coming from?

**Comment by kierangillen** [comment]
Those will come from the gravity migration in step 2. So all the offsets will be new. Step 1 is to ensure that the status quo for `start_at` and `end_at` doesn't change from the migration.

**Comment by dleve123** [comment]
@anandaroop 

> local time of the event
> timezone of the event
> UTC time of the event (derived from form submission, or any at later time)

I know we are discussing shortly, but can we give an example of 3 such values. I think "local time of th event" can be interpretted differently.

**Comment by alloy** [comment]
@dleve123 @anandaroop How about “time of the event in the specified timezone”?

**Comment by alloy** [comment]
@kierangillen I feel like I’m missing something about the order of things, but I guess that will become apperant as work progresses.

**Comment by joeyAghion** [comment]
Taking some notes for myself here:

Any chosen time can manifest in a few ways:
* The system wants to schedule something or programmatically act on it. In these cases, the stored value must be absolute or trivially convertible to an absolute value, so UTC (the only un-changing time form) is preferred.
* A related case is when we want to render a countdown or the time _until_ a given, absolute time value. Again, UTC is preferred.
* We want to render it in the context of a viewer's time and place ("sale starts at 4pm your time"). This appears to require a viewer's offset from UTC _at the time_ [in the past of future] of the event. Is that even possible or practical, e.g., based on browser headers or devices?
* We want to render it in the context of a specific time/place, such as that of a show or fair in the past or future. If I understand correctly, a time _zone_ isn't sufficient for this but an offset from UTC may be.

Note that even shows can be "online-only" (and maybe fairs in the future), so we should not assume there's always a location relevant to an event.

This implies to me that we should always aim to store in UTC or something trivially convertible to UTC, such as with offsets. (Because of the potential for confusion, we should only store offsets in the core time fields if they meaningfully improve how we are able to render those values to end users.) This isn't _that_ different from how the data is already modeled, though we may want to store additional fields for friendlier rendering.

This brings us to the major obstacle: we need a more sophisticated UI affordance for inputting time values that eventually get stored as an absolute value. This affordance could consider browser headers or associated location _by default_, but because of all the scenarios possible (e.g., I'm in NYC inputting an event for a fair in Switzerland in the future, after clocks change), it would be important to allow modifying the presumed offset or zone.

**Comment by kierangillen** [comment]
Notes from meeting from today: 

Product Desires:

- As an admin, I should always specify a timezone when entering a datetime in an Artsy tool.
- As a partner admin, I should always specify a timezone when entering a datetime in an Artsy tool.
- As a client developer querying Metaphysics, I want to be able to query for a “dumb” date time string(s), i.e. “4:00 PM ET”
- As a client developer querying Metaphysics, I want to be able to query for a UTC datetime for “important” date times
 - I.e auction start times
- As a data stakeholder, I want to be able to re-calculate accurate UTC time for a given local time and timezone.


Tech perspective:

- Audit current date times to determine accuracy-sensitive times.
 - goal: identify date times where accuracy affects user experience.
 - gravity
 - exchange
 - (others)
- Try to put as much timezone view logic into metaphysics when possible
 - reduce duplicate calls to moment/other JS
- Really important that the data layer makes it easy to convert to UTC

Proof of concept:
 (1) adding UI for partner show events in cms.artsy.net
 (2) change kinetic / add validations / gravity to ensure that this date time always have a paired timezone
   - adding database columns, constraints, UTC derivation
   - persisted derived UTC time in gravity as well (in addition to local time and timezone)
   - migration: assume that timezone of partner show event is derived from the location object.

—

 (3) Make Metaphysics source of truth for any date/time/range formatting
 (4) Update clients of Metaphysics to use the new MP fields

Order of events:

- [Kieran & Owen]: Audit current needs for time stuff, implement some new fields in metaphysics which reflect those needs
 - Document requirements in Notion, spike on Metaphysics field implementations.
- [Roop]: Do the audit.

- regroup first of April to review spike with Kieran.

—

{ local_time: “4 pm”, tz: “ET”, computed_utc_time: “some-utc-time” }

**Comment by anandaroop** [comment]
@joeyAghion I think your notes sum it up well. Couple of minor points.

> • We want to render it in the context of a specific time/place, such as that of a show or fair in the past or future. If I understand correctly, a time zone isn't sufficient for this but an offset from UTC may be.

If you have the _correct_ UTC time in the database, and a desired timezone to localize to, I think that is sufficient, assuming that you are leaning on an up-to-date timezone database (via OS or library).

> Note that even shows can be "online-only" (and maybe fairs in the future), so we should not assume there's always a location relevant to an event.

Good point — and why we would _try_ to provide a sensible default in the UI for selecting a timezone, but allow user to override. 

> This implies to me that we should always aim to store in UTC or something trivially convertible to UTC … though we may want to store additional fields for friendlier rendering.

We may store extra fields in the db in order to convert (and re-convert) _to_ correct UTC. But converting _from_ UTC to friendly text shouldn't involve new stored fields, just new derived "fields" in the GraphQL layer.

> This brings us to the major obstacle: we need a more sophisticated UI affordance for inputting time values that eventually get stored as an absolute value. This affordance could consider browser headers or associated location by default, but because of all the scenarios possible (e.g., I'm in NYC inputting an event for a fair in Switzerland in the future, after clocks change), it would be important to allow modifying the presumed offset or zone.

I'm less sure that we'll want to leverage the user's TZ in the case of admin or partner use cases, but this otherwise sounds 👍.

**Comment by SamRozen** [comment]
Sorry for missing the meeting yesterday, one quick though I'd like to bring up in case if was not raised, regarding:
> As an admin, I should always specify a timezone when entering a datetime in an Artsy tool.
> As a partner admin, I should always specify a timezone when entering a datetime in an Artsy tool.

We already know that it's difficult for people to input high quality data. What can we do to make human operator's life as easy as possible? Can we bootstrap timezone from location and just ask them to validate? What other ideas are we considering?

**Comment by anandaroop** [comment]
> Can we bootstrap timezone from location and just ask them to validate

We'll be starting this effort with `PartnerShowEvents` (e.g. opening receptions), and what you suggest is exactly the plan. Every one of these _should_ always have an associated location, and thereby a timezone.

(`PartnerShowEvent` ⤚ `PartnerShow` ⤚ [`PartnerLocation`](https://github.com/artsy/gravity/blob/d897ea6c72964875b45631459bd681b3372f8aba/app/models/domain/partner_location.rb#L24))

**Comment by kierangillen** [comment]
I'm going to close this issue as we have for action and another platform for discussion.
