### ISSUE TITLE
[Logging] Send out alerts if failing queries increases.

### ISSUE THREAD

**Issue by alloy** [artsy/metaphysics#341]
These should already return 4xx HTTP statuses, so NewRelic should simply have a proper error rate alert that notifies us, e.g. in Slack #platform-alerts.

**Comment by alloy** [comment]
We log errors, but we disabled NewRelic’s alerting because it was too noisy at first. I _think_ we can try enabling it again, unless you have any objections @joeyAghion?

**Comment by joeyAghion** [comment]
New Relic alerting is already enabled and we do occasionally receive notifications in the #platform-alerts Slack channel when the error rate exceeds its thresholds (1% for 10 minutes or 5% for 5, I believe). Most errors still appear to be 4XX-like.

> These should already return 4xx HTTP statuses, ...

Are you sure about that⬆️? I thought responses were always 200s due to the difficulty of interpreting response codes cascading from potentially-multiple backend requests.

**Comment by alloy** [comment]
It’s hard to say, but I think I meant that we were already reporting 4XX HTTP statuses to NewRelic.

Thanks for the update, closing this!
