### ISSUE TITLE
is_price_range should be false for multiple editioned works at distinct price points

### ISSUE THREAD

**Issue by mzikherman** [artsy/metaphysics#497]
re: https://github.com/artsy/collector-experience/issues/66

**Comment by xtina-starr** [comment]
@mzikherman question regarding this, if `sale_message` takes into account the edition sets and whether they are sold or should be displayed as a range, wouldn’t that be the case for price as well? Since they are both using `display_price`. I’m unclear about what the addition work would be here. I'm thinking if there are two sets and one is sold like `sale_message` wouldn't `price` also take that into account and return an exact price in the case of https://www.artsy.net/artwork/julian-charriere-panorama-52-degrees-31-10-dot-80-n-13-degrees-24-44-dot-11-e-1

**Comment by mzikherman** [comment]
Closed in https://github.com/artsy/metaphysics/pull/498

No additional work needed!
