### ISSUE TITLE
RFC: Update `isTypeOf` checks to use injected type data, rather than inspecting responses

### ISSUE THREAD

**Issue by mzikherman** [artsy/metaphysics#865]
These kinds of `isTypeOf` checks: https://github.com/artsy/metaphysics/blob/da9771e6aafbbffd03761d6a1678da32a673b1a7/schema/me/conversation/index.js#L328 (which is a pattern we follow everywhere), can be brittle.

Generally speaking we've been a little bit hasty (IMO), in making certain type and null-ability assertions in Metaphysics. For instance, unless there's a database constraint on a field in Impulse's Postgres database, you really _can't_ declare that field to be `GraphQLNonNull`. Even if there are validations or business logic in Impulse that should prevent that from happening, it could still happen without that database constraint. There might be an opportunity to review some of those in Impulse's schema (and others): https://github.com/artsy/impulse/blob/83c566553eeb8402ef33b6e7fe49ed4b7a19e2ad/db/schema.rb

Since we now have loaders per-type, we know before we fetch something using a loader what type it is. This should make it trivial to inject a `_type_of_` (or some new 'reserved' field), and then we switch the `isTypeOf` to check that.

Here's an example using `Tag`:

https://github.com/artsy/metaphysics/blob/da9771e6aafbbffd03761d6a1678da32a673b1a7/schema/tag.js#L49-L50, with the `isTypeOf` check just being: `obj._type === "Tag"`

**Comment by alloy** [comment]
Ohh, interesting strategy to use the loaders! Hadn’t thought of that yet. I think this makes a lot of sense, seeing as we don’t really have any feed that mixes types, do we? Because that’s the only place this could break.

With regards to nullable fields, _where possible_ I would rather we add those constraints to the db instead of loosening the types for clients. Would it be possible in the case you’re currently thinking of? I’m not really sure why the nullability is mentioned in this RFC, though, can you elaborate on the connection?

**Comment by mzikherman** [comment]
We found a conversation in production (possibly many conversations), that were failing our `isTypeOf` checks, b/c one of those fields _is_ actually nullable (and is then not even included in the response by the Impulse presenter, which strips nulls).

**Comment by alloy** [comment]
Ahhh, I see, gotcha.
