### ISSUE TITLE
metaphysics alerts

### ISSUE THREAD

**Issue by joeyAghion** [artsy/metaphysics#932]
(Related to https://github.com/artsy/metaphysics/issues/931, which describes common failure scenarios.)

Metaphysics' instability issues have revealed that it lacks some of the usual "production checklist" items, like alerts. We usually respond to issues in _other_ systems, then find that they actually originate in Metaphysics. There's wasted effort in that, and really Metaphysics should have its own alert on at least **latency**, **error rate**, and maybe **memory** (since that's been a problem area).

**Comment by izakp** [comment]
Looks like this is due to the NewRelic integration.  Once I [disabled it on Saturday 17th Feb, 12:00 CET](https://artsy.slack.com/archives/C2TQ4PT8R/p1518866332000077) memory usage became consistent and errors subsided.

The NewRelic integration points look very suspicious.  The `graphqlErrorHandler` function is requiring the `newrelic` library [in the context of the request handler](https://github.com/artsy/metaphysics/blob/master/src/lib/graphql-error-handler.js#L3).  Furthermore, this custom middleware function is being [patched into the app](https://github.com/artsy/metaphysics/blob/master/src/index.js#L6), while at the same time our own [artsy-newrelic library](https://github.com/artsy/artsy-newrelic) [is being patched in](https://github.com/artsy/metaphysics/blob/master/index.js#L2)  why this middleware is being patched in twice and in the context of every request, I have no idea but it seems like a really bad pattern. Refactor this and I suspect our problems will become clear.

**Comment by alloy** [comment]
There is no issue with how those imports are setup. Node modules are only loaded once and then cached, so you can import it many times all over the place and always get the same instance.

**Comment by izakp** [comment]
Thanks @alloy for https://github.com/artsy/metaphysics/pull/935

**Comment by joeyAghion** [comment]
Gonna close this as we've since added alerts on error rate (exceeding 5%) and response time (95th percentile exceeding 4 seconds). These deliver to the platform-alerts@ group and #platform-alerts slack channel.
