### ISSUE TITLE
Host the app in a different place

### ISSUE THREAD

**Issue by mzikherman** [artsy/metaphysics#96]
This repo can chew up a lot of cache space when in production and serving high traffic pages.

Heroku cache/redis instances are pretty expensive especially for the larger ones which are needed.

I propose one of the following three choices:
- keep everything on heroku and accept that the redis instance is going to be $$
- keep the app on heroku and use AWS ElasticCache (this may have security policy or other implications)
- deploy the app fully to OpsWorks and use AWS ElasticCache

**Comment by mzikherman** [comment]
http://docs.aws.amazon.com/opsworks/latest/userguide/workinglayers-node.html

**Comment by alloy** [comment]
@joeyAghion @mzikherman Should ‘platform’ pick this up? And should it be done soon or some undetermined time in the future?

**Comment by joeyAghion** [comment]
@alloy looks like we made some changes as a result of this: https://trello.com/c/656uauKM/1461-upgrade-metaphysics-cache (private link).

We can still capture some savings but important to understand if the situation has changed since then and by how much $. There's an open question on that card, BTW.

I don't think this has to drive a switch from Heroku to Opsworks, since we can switch memcache providers independently. Looking at the current Heroku resources allocated to this, though, much of the cost _is_ a product of the dyno size/number.

**Comment by alloy** [comment]
Thanks @joeyAghion, that makes a lot of sense. I’m going to first see if we can get our dyno requirements scaled down a bit and, if needed, we can revisit this idea in the future.
